sudo: required
language: ruby
addons:
  postgresql: "9.4"
  apt:
    - chrome
rvm:
 - "2.2.1"
cache: bundler
bundler_args: --without production development
before_install:
  - # Start headless chrome
  - google-chrome-stable --headless --disable-gpu
  - gem install bundler

before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:drop db:create db:migrate
script:
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - chromedriver --version
  - RAILS_ENV=test bundle exec rake assets:precompile
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec rake sunspot:solr:stop